server:
    port: 9092

eureka:
    instance:
        hostname: localhost
        port: 9091
    client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: segprev
            client-secret: $2a$10$SLXAYmuPqZhmqsyTPpn2MOB14XWbQ4JMZ4thyQvwvg9N.stf4x8yC
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        url: jdbc:derby://localhost:1527/oauth2-segprev
        username: hiro
        password: hiro
        driver-class-name: org.apache.derby.jdbc.ClientDriver
        schema: classpath:/sql/ddl-Derby.sql
        data: classpath:/sql/dml-Derby.sql
    jpa:
        show-sql: true
        open-in-view: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
